#!/bin/bash

# Prints the backlight percentage
# Requires the light package

PREFIX='󰛨 '

get_backlight()
{
    echo "$PREFIX $(xrandr --verbose --current | grep "Brightness" | grep -oE '[^ ]+$' | grep -oE '..$')%"
}

get_backlight
