#!/bin/bash

# Deps:
# 	curl


get_weather()
{
	RESPONSE="$(curl --max-time 5.0 -s 'wttr.in/?format=%C+%t\n')"
  if ![[ ${#RESPONSE} -lt 40 ]] then
  	RESPONSE=" N/A "
	fi

	echo "$RESPONSE"
}


if [ $(( 10#$(date '+%S') % 30 )) -eq 0 ]; then
	get_weather
fi
